-- Table to track when a user has read a message
CREATE TABLE IF NOT EXISTS public.message_read_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id uuid NOT NULL, -- This will reference an ID from either dm_messages or chat_messages
    user_id uuid NOT NULL,
    read_at timestamptz DEFAULT now() NOT NULL,

    CONSTRAINT fk_user
        FOREIGN KEY(user_id)
        REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Add a unique constraint to prevent duplicate entries for performance and correctness
CREATE UNIQUE INDEX IF NOT EXISTS message_read_statuses_unique_idx ON public.message_read_statuses (message_id, user_id);

-- Enable Row Level Security
ALTER TABLE public.message_read_statuses ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES
-- Users can see their own read statuses
CREATE POLICY "Users can see their own read statuses"
ON public.message_read_statuses FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own read statuses
CREATE POLICY "Users can insert their own read statuses"
ON public.message_read_statuses FOR INSERT
WITH CHECK (auth.uid() = user_id);